BEGIN;

-- Schema persisten RAG yang terpisah dari tabel aplikasi SDM utama.
-- pgvector menyimpan embedding 384 dimensi dan HNSW mempercepat cosine search.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS rag AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS rag.schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rag.documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL UNIQUE,
  title text,
  source_type text NOT NULL DEFAULT 'knowledge',
  selection_code text,
  selection_year integer,
  authority text,
  effective_date date,
  sha256 char(64),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rag.chunks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint NOT NULL REFERENCES rag.documents(id) ON DELETE CASCADE,
  chunk_no integer NOT NULL,
  page integer,
  content text NOT NULL,
  content_hash char(64) NOT NULL,
  token_count integer,
  embedding vector(384),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_id, chunk_no),
  UNIQUE (document_id, content_hash)
);

CREATE TABLE IF NOT EXISTS rag.ingestion_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running',
  source_count integer NOT NULL DEFAULT 0,
  chunk_count integer NOT NULL DEFAULT 0,
  embedding_model text,
  embedding_dimensions integer,
  error jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS chunks_document_idx ON rag.chunks (document_id, chunk_no);
CREATE INDEX IF NOT EXISTS chunks_fts_idx ON rag.chunks USING gin (to_tsvector('simple', content));
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'rag.chunks'::regclass AND attname = 'embedding'
      AND atttypmod = -1
  ) THEN
    ALTER TABLE rag.chunks ALTER COLUMN embedding TYPE vector(384)
      USING CASE WHEN embedding IS NULL THEN NULL ELSE embedding::vector(384) END;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw_idx ON rag.chunks USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;
CREATE INDEX IF NOT EXISTS documents_selection_idx ON rag.documents (selection_code, selection_year) WHERE is_active;

INSERT INTO rag.schema_migrations(version)
VALUES ('001_rag_pgvector')
ON CONFLICT (version) DO NOTHING;

GRANT USAGE ON SCHEMA rag TO user_personel;
GRANT SELECT ON rag.documents, rag.chunks, rag.ingestion_runs TO user_personel;

COMMIT;
